# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  Polly:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      working-directory: /home/runner/work/Web-APIs/Web-APIs/Polly/
      run: dotnet restore
    - name: Build
      working-directory: /home/runner/work/Web-APIs/Web-APIs/Polly/
      run: dotnet build --no-restore
    - name: Test
      working-directory: /home/runner/work/Web-APIs/Web-APIs/Polly/
      run: dotnet test --no-build --verbosity normal
  GraphQL:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      working-directory: /home/runner/work/Web-APIs/Web-APIs/GraphQL/
      run: dotnet restore
    - name: Build
      working-directory: /home/runner/work/Web-APIs/Web-APIs/GraphQL/
      run: dotnet build --no-restore
    - name: Test
      working-directory: /home/runner/work/Web-APIs/Web-APIs/GraphQL/
      run: dotnet test --no-build --verbosity normal
